# Generated by Django 4.0.3 on 2022-05-17 09:03

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[(1, 'Admin'), (2, 'Teacher')], default=1, max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='GiangVien',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ten_gv', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('gioitinh', models.CharField(max_length=3, null=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Khoa',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tenkhoa', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MonHoc',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ten_mon', models.CharField(max_length=255)),
                ('mo_ta', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SinhVien',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ten_sv', models.CharField(max_length=128)),
                ('gioitinh', models.CharField(max_length=3)),
                ('anhthe', models.FileField(null=True, upload_to='')),
                ('khoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students_attendance_app.khoa')),
            ],
        ),
        migrations.CreateModel(
            name='VectorDacTrung',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vector_dt', models.TextField()),
                ('sinhvien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_attendance_app.sinhvien')),
            ],
        ),
        migrations.CreateModel(
            name='LopHocPhan',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ten_lophp', models.CharField(max_length=255)),
                ('kyhoc', models.CharField(max_length=255)),
                ('giangvien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_attendance_app.giangvien')),
                ('mon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students_attendance_app.monhoc')),
            ],
        ),
        migrations.AddField(
            model_name='giangvien',
            name='khoa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students_attendance_app.khoa'),
        ),
        migrations.CreateModel(
            name='DiemDanh',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('buoi_1', models.BooleanField(default=False)),
                ('buoi_2', models.BooleanField(default=False)),
                ('buoi_3', models.BooleanField(default=False)),
                ('buoi_4', models.BooleanField(default=False)),
                ('buoi_5', models.BooleanField(default=False)),
                ('buoi_6', models.BooleanField(default=False)),
                ('buoi_7', models.BooleanField(default=False)),
                ('buoi_8', models.BooleanField(default=False)),
                ('buoi_9', models.BooleanField(default=False)),
                ('buoi_10', models.BooleanField(default=False)),
                ('buoi_11', models.BooleanField(default=False)),
                ('buoi_12', models.BooleanField(default=False)),
                ('buoi_13', models.BooleanField(default=False)),
                ('buoi_14', models.BooleanField(default=False)),
                ('buoi_15', models.BooleanField(default=False)),
                ('lophocphan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_attendance_app.lophocphan')),
                ('sinhvien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_attendance_app.sinhvien')),
            ],
        ),
        migrations.CreateModel(
            name='AnhNhanDien',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('embeddings', models.TextField()),
                ('sinhvien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_attendance_app.sinhvien')),
            ],
        ),
        migrations.CreateModel(
            name='AdminHOD',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
