# Generated by Django 4.0.3 on 2022-05-27 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_attendance_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnhNhanDien',
        ),
    ]
